source ~/.config/nushell/libs/ansix/colorschemes.nu
source ~/.config/nushell/libs/ansix/ansix.nu
source ~/.config/nushell/libs/eprompt/themes.nu
source ~/.config/nushell/libs/other.nu
source ~/.config/nushell/libs/eprompt/eprompt.nu
source ~/.config/nushell/libs/cross.nu
source ~/.config/nushell/libs/spwd.nu
source ~/.config/nushell/personal/prompts/eldyj.nu
source ~/.config/nushell/personal/other.nu
